### PR TITLE
Describe Docker-based setup for dev env

### PR DESCRIPTION
**Pull request by bajtos**
@superkhau PTAL. Could you please go through the steps I described in README yourself, to verify they are correct and complete?

Connect to strongloop-internal/scrum-loopback#1126

### CODE REVIEW

**Comment by bajtos** [comment]
@superkhau ping

**Comment by superkhau** [comment]
@bajtos Sorry for the late response, I finally got around to getting back into the groove after the trip, will test tomorrow.

**Comment by bajtos** [comment]
@superkhau ping

**Comment by superkhau** [comment]
@bajtos Sorry I never got around to getting this working -- I'll ask ritch to see where it lies in our priorities. @ritch Can we get this planned? I tried last time for a day and couldn't get it working on my machine (kept using up all my memory). Or we could reassign to someone else to figure out depending on the missions planned.

**Comment by superkhau** [comment]
May need to find Paul Chen to help out with running the docker image locally on my machine.

**Comment by bajtos** [comment]
@superkhau @ritch let's get these instructions merged, so that we have at least something to get started. We can always improve them later if needed.

**Pull request merged**
