### PR TITLE
Enable integration tests on CI

### PR DESCRIPTION
**Pull request by bajtos**
We need CI infrastructure to point to eXtremeScale server to make the checks pass.

cc @superkhau @rmg 

Connect to strongloop-internal/scrum-loopback#1127

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed, at last.

Thank you @rmg for your help!

**Pull request merged**
